export default {
    name:'flyPattern',
    title:'Fly Pattern',
    type:'document',
    fields: [
        {
            name:'id',
            title:'ID',
            type:'number'
        },
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'type',
            title:'Type',
            type:'string'
        },
        {
            name:'hook',
            title:'Hook',
            type:'string'
        },
        {
            name:'thread',
            title:'Thread',
            type:'string'
        },
        {
            name:'rib',
            title:'Rib',
            type:'string'
        },
        {
            name:'hackle',
            title:'Hackle',
            type:'string'
        },
        {
            name:'body',
            title:'Body',
            type:'string'
        },
        {
            name:'wing',
            title:'Wing',
            type:'string'
        },
        {
            name:'head',
            title:'Head',
            type:'string'
        },
        {
            name:'tail',
            title:'Tail',
            type:'string'
        },
        {
            name:'imgUrl',
            title:'ImgUrl',
            type:'url'
        },
        {
            name:'video',
            title:'TyingVideo',
            type:'url'
        },
    ]
}